apiVersion: v1
kind: Service
metadata:
  name: website-project-service #Rename this to your project name
  labels:
    app: website-project #Rename this to your project name
spec:
  selector:
    app: website-project
  ports:
  - port: 80 #Change this to your project port
    targetPort: 3000 #Change this to your project port
    protocol: TCP
  type: ClusterIP #W/e use using LoadBalancer,NodePort, etc.
